[workspace]
resolver = "2"

members = [
    "_lib",
    "algorithms",
    "basic-challenges",
    "complexity-analysis",
    "data-structures",
    "design-patterns",
    "dsa",
    "dynamic-programming",
    "macros",
    "problem-solving",
    "projects/pandas",
    "projects/snake",
]
