[package]
name = "data-structures"
version = "0.1.0"
edition = "2021"

[dependencies]


[[bin]]
name = "ds001"
path = "./ds001_find_missing_number.rs"

[[bin]]
name="ds002"
path="./ds002_longest_subarray.rs"
